baseurl = "https://blog.inthepuddle.net/"
languageCode = "ja"
hasCJKLanguage = "true"
enableRobotsTXT = "true"
title = "blog.inthepuddle.net"
theme = "hugo_theme_robust"
googleAnalytics = "UA-118994093-1"
disqusShortname = "bloginthepuddle"

[params]
  description = ""
  dateformat = "Jan 2, 2006"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700"
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif"
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.jpg"
  name = "白木 良平"
  description = ""

[outputs]
page = [ "HTML", "AMP" ]
